[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = {version = "0.29.0", features = ["all-widgets"]}
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.143"
uuid = { version = "1.18.1", features = ["serde", "v4"] }
